# Generated by Django 4.0.3 on 2025-03-24 13:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0003_maintenanceschedule'),
    ]

    operations = [
        migrations.AddField(
            model_name='farmtool',
            name='tool_image',
            field=models.ImageField(blank=True, default='tractor.jpg', upload_to=''),
        ),
    ]
