# Generated by Django 5.2.1 on 2025-05-07 15:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0004_farmtool_tool_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='tooltransaction',
            name='transaction_id',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='farmtool',
            name='tool_image',
            field=models.ImageField(blank=True, null='True', upload_to='images'),
        ),
        migrations.AlterField(
            model_name='tooltransaction',
            name='status',
            field=models.CharField(choices=[('Checked Out', 'Checked Out'), ('Checked In', 'Checked In')], max_length=100),
        ),
    ]
